[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "crewai>=0.118.0",
    "langchain>=0.3.24",
    "langchain-anthropic>=0.3.12",
    "openai>=1.76.2",
    "pyyaml>=6.0.2",
]
