steps:
  # Build the container
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/tarefo-ai:$COMMIT_SHA',
      '.'
    ]
    id: 'build-container'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tarefo-ai:$COMMIT_SHA']
    id: 'push-container'
    waitFor: ['build-container']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'gcr.io/$PROJECT_ID/tarefo-ai:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
    id: 'deploy-cloud-run'
    waitFor: ['push-container']

images:
  - 'gcr.io/$PROJECT_ID/tarefo-ai:$COMMIT_SHA'

timeout: '1800s'
